Namespaces:
  API:
      Port: 443
      Protocol: "https"
      Link: "/login"
  FE:
      Port: 3000
      Protocol: "https"
      Link: "/"
      SSRCheck: true
      SSRThreshold: 5048

OpenSearch:
  Hosts:
  - "http://localhost:9200"
  Index: "service_check"
  Username: "admin"
  Password: "admin"

Hosts:
  - "API01-192.168.1.2"
  - "API02-192.168.1.3"
  - "API03-192.168.1.4"
  - "FE01-192.168.1.2"
  - "FE02-192.168.1.3"
  - "FE03-192.168.1.4"